-- First, remove the table if it exists
DROP TABLE IF EXISTS noteful_folders;

-- Create the table anew
CREATE TABLE noteful_folders (
  id INTEGER primary key generated by default as identity,
  name TEXT NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO noteful_folders (name)
VALUES
  ('Important'),
  ('Super'),
  ('Spangley');